# Generated by Django 2.0.6 on 2018-10-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=30)),
                ('login', models.TextField(max_length=25)),
            ],
        ),
    ]
